### ISSUE TITLE
Max. No. of Images resets to 4

### ISSUE THREAD

**Issue by markwaters** [janboddez/share-on-mastodon#104]
Not sure if this is a bug or intentional.
Settings , Share on Mastodon , Images , Max. No. of Images.
Set to 4 , Save , = 4.
Set to 3 , Save , = 3.
Set to 2 , Save , = 2.
Set to 1 , Save , = 1.
Set to 0 , Save , = resets to 4. ?!

**Comment by janboddez** [comment]
That's weird, my validation function should accept 0 as a valid option. The default is 4, though (which is also the max Mastodon supports), so I guess it somehow discounts 0 as valid and then falls back to 4.

Either way, if you don't want any images to get crossposted, can always simply disable all checkboxes (and, if applicable, remove any filters you may have set earlier, for older plugin versions).

**Comment by janboddez** [comment]
The issue seems to be here:
https://github.com/janboddez/share-on-mastodon/blob/188ca078c10b409fbdfe48b99615536631bb025d/includes/class-options-handler.php#L463

`! empty( $this->options['max_images'] )` should become `isset( $this->options['max_images'] )`.

**Comment by janboddez** [comment]
I'll verify this later and fix it in the next version.
