### ISSUE TITLE
"Validation failed" when posting through JetPack with hook

### ISSUE THREAD

**Issue by jsit** [janboddez/share-on-mastodon#107]
I have "Always share on Mastodon" checked, and I have this hook in my theme's `functions.php`:

```php
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
  if ( 'status' === get_post_format( $post ) ) {
    $status = wp_strip_all_tags( $post->post_content );
    return $status;
  } else {
    return null;
  }
}, 10, 2 );
```

This works fine when posting through WP Admin, and curiously it works when posting from MarsEdit, but when posting from the JetPack app, (a) the post doesn't get shared to Mastodon, and (b) the post shows this message in the edit screen:

> Validation failed: Text can't be blank

<img width="286" alt="Screenshot 2024-05-05 at 2 35 45 PM" src="https://github.com/janboddez/share-on-mastodon/assets/643417/2d7c704f-4042-4eb4-bbf2-dd86ef2bef87">

Is this expected behavior, is it a bug, or am I doing something wrong?

**Comment by janboddez** [comment]
Yeah, you shouldn't return `null`. `$status` has to be a non-empty string, as it is the text you're posting to Mastodon.

Maybe you want to disable federation for non-status posts? In that case you should probably use the `share_on_mastodon_enabled` filter. (I need to update the docs!)

**Comment by janboddez** [comment]
To disable the cross-posting of anything that isn't a status, you'd use an additional filter, something like (untested):
```
add_filter( 'share_on_mastodon_enabled', function( $is_enabled, $post_id ) {
  if ( 'status' !== get_post_format( $post_id ) ) {
    // Only cross-post statuses.
    $is_enabled = false;
  }

  return $is_enabled;
}, 10, 2 );
```

**Comment by janboddez** [comment]
> The return value has to be a non-empty string, as it is the text you're posting to Mastodon.

Guessing it _could_ be blank if there was an image. I should check that.

**Comment by janboddez** [comment]
If the post _is_ a "status" and there _is_ text (i.e., a non-empty post content), then it _may_ be a bug, though, and likely has to do with how WordPress' REST API works (i.e., it first saves the post, and _only then_ sets the post format).

You might be able to work around _that_ by setting a "delay" (of only, I don't know, 10 or so seconds). (Still, `$status` should probably not be `null`, ever.)

**Comment by jsit** [comment]
> If the post _is_ a "status" and there _is_ text (i.e., a non-empty post content), then it _may_ be a bug, though, and likely has to do with how WordPress' REST API works (i.e., it first saves the post, and _only then_ sets the post format).

Yeah, that's why this surprised me -- I didn't expect it to even _get_ to the `return null`, since there is content, and when posting via the web UI, it works with this same hook in place.

**Comment by janboddez** [comment]
So ... you're certain the post format was set?

Guessing the app is doing something different then ...

Would you mind trying setting a delay? I think a couple seconds should be plenty, but it doesn't hurt to also try out, e.g., 60 seconds. (Note that WP's cron system is notoriously inaccurate, so posts could always come through _later_.)
