### ISSUE TITLE
Scheduled posts are not automatically shared

### ISSUE THREAD

**Issue by cybeardjm** [janboddez/share-on-mastodon#121]
My settings: opt-in is on & delay = 120

I scheduled 2 posts and activated the "share on Mastodon" option for both posts.
Both were normally published but didn't appear on my Mastodon TL.

When going back to edit the posts, they're still marked as activated, but no link below the box.
Just saving/"Updating" the posts (no other change), sends them to Mastodon.

**Comment by janboddez** [comment]
Sounds like #98. Problem is I could not replicate. Maybe something's changed and it really is broken now.

In theory, when you click "Schedule," the checkbox value gets saved to the database.

Then when the post is published by WP's "WP-Cron functionality," the [`save_post_{$post->post_type}`](https://github.com/WordPress/wordpress-develop/blob/5655cdf203d443b6c81fce976663a4ecb8ca355b/src/wp-includes/post.php#L5062) hook is run, which triggers crossposting. Same hook that's run when publishing right away.

**Comment by janboddez** [comment]
@cybeardjm Does this still happen?

If so, I added a bunch of debug logging statements to the latest `main`. Was wondering if you'd be up for trying to completely replace your copy of the plugin with the files found at https://github.com/janboddez/share-on-mastodon/archive/refs/heads/main.zip ... (Like, after unzipping, just rename the folder to `share-on-mastodon`, delete the original plugin, and replace by the "new" one.)

**Comment by cybeardjm** [comment]
Hi @janboddez haven't posted scheduled posts for a while but have a few coming...
Will tell you then, and sure, can try the updated version.

**Comment by cybeardjm** [comment]
Ok, first scheduled post published tonite. Everything went smoothly and it was properly autoposted to my timeline.
