### ISSUE TITLE
It's stopped working in latest version

### ISSUE THREAD

**Issue by keynet** [janboddez/share-on-mastodon#122]
No errors, reset the config and re-authorised. No errors, says authorised but doesn't work any more

**Comment by janboddez** [comment]
By last version, do you mean going from 0.19.0 to 0.19.1? Or compared to an even older version? (Version 0.19.0 introduced some database changes _that should not_ affect existing installs.)

You could check if it works for older version over on: https://wordpress.org/plugins/share-on-mastodon/advanced/. I mean, you could try and manually installed one of the older version under Advanced > Previous Versions on that page.

I think the main change in v0.19.1 was in how the "default" (i.e., share/don't share) is set/stored, prior to it being saved to the database, and how it treats "older" posts (to prevent them from being share outside your control).

Have you tried enabling debug logging?

The posts it doesn't work for, are they in any way different than before?

After re-authorizing, does it say you've successfully authorized? Also after refreshing the settings page? When you log in to Mastodon and visit Preferences > Account > Authorized Apps, is "Share on Mastodon" listed?

Do you use the classic editor, or the block editor? Does the sharing toggle/checkbox on the Edit/Create Post screen reflect whatever you set it to, immediately after publishing and also after refreshing the entire page? (Would it be possible to check the `postmeta` table in the database to see what value is stored? _If_ you have database access, I might ask some follow-up questions via email or so.)
