### ISSUE TITLE
Use underscore prefixes for meta keys

### ISSUE THREAD

**Issue by jsit** [janboddez/share-on-mastodon#123]
Using underscore prefixes for meta keys (e.g. `_mastodon_permalink`) will prevent these keys from showing up in the Custom Fields metabox. It would be nice not to have those in there, since they are not likely to be manually edited.

**Comment by janboddez** [comment]
`_mastodon_permalink` is definitely not something set by this plugin.

I used underscored meta fields for (nearly) everything, e.g., https://github.com/search?q=repo%3Ajanboddez%2Fshare-on-mastodon%20_share_on_mastodon_url&type=code.

**Comment by jsit** [comment]
Oh shoot, I'm so sorry. These are from an old plugin that I forgot I had even used. Apologies!
