### ISSUE TITLE
feature: include post excerpt

### ISSUE THREAD

**Issue by atomGit** [janboddez/share-on-mastodon#13]
it looks like there currently isn't a way to include a post excerpt in the 'toots' - when i publish a post, i'm only seeing the headline on mastodon

can the filters be used for this?

**Comment by janboddez** [comment]
Yep, this is possible using a filter hook. Here's an (untested) example that should show the excerpt and a permalink:

```
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
  $status = wp_strip_all_tags(
    html_entity_decode( get_the_excerpt( $post ), ENT_QUOTES | ENT_HTML5, get_bloginfo( 'charset' ) )
  );
  $status .= "\n\n" . get_permalink( $post );
  return $status;
}, 10, 2 );
```

Couple notes:

You don't _have_ to strip all HTML from statuses. Mastodon supports some tags and will encode others. It's a bit of an easy way out on my part.

Also, Mastodon will encode ampersands and stuff, hence the `html_entity_decode()` call in there to prevent double encodes. (As a result, in the rare case that there's ever (encoded) HTML in your excerpts, that would get stripped, too. Feel free to experiment with this, that's what these hooks are for.)

If all this results in a status being over 500 characters, Mastodon won't accept it. (I myself am okay with that: short excerpts get posted to Mastodon, longer ones are visible on my blog only. [I use a very similar implementation, by the way.])

There _is_ also a (still undocumented) filter that allows for overriding this behavior. It'll just cut of statuses that are too long. (Which may mess up permalinks and things at the very end of a status.) A developer could probably come up with their own solution, though. (Again, that's what the filters are for.)

You'd add this to your child theme's `functions.php` or a site-specific plugin. ("Must-have plugins" are great for this!)

Here's a couple more examples of what's possible (look under "Custom Formatting", like appending tags, etc.): https://jan.boddez.net/wordpress/share-on-mastodon.

**Comment by atomGit** [comment]
thanks for this Jan

is there a way to grab the first 500 chars so all WP posts are published on Mastodon (i assume this would have to include the title also)? in my case i'd rather decide whether to publish on Mastodon using the 'Share on Mastodon' option rather than have Mastodon decide based on the char count

also i think this option (excerpt [bool] and excerpt length [int] ) would be well worth adding to the settings UI - i'm sure i'm not the only one that would benefit

**Comment by atomGit** [comment]
...also, the permalink would have to be included in the excerpt char count (and blank lines as well) - i guess that makes it a little harder on your end

**Comment by janboddez** [comment]
It's kind of basic, but if you also add `add_filter( 'share_on_mastodon_cutoff', '__return_true' );`, it'll post longer messages, too (and abruptly cut them short if needed). That is, it uses `mb_substr()`, so it could still be that Mastodon, which I _think_ uses the "Ruby equivalent of `substr()`," rejects a too long post with certain emoji or other multibyte characters in them. I may eventually make this more robust.

This will run _after_ the filter above is applied. A (future?) smarter version of it would grab the first x words or characters and only then append the permalink ...

I deliberately keep the options page as simple as possible, but allowing end-users to choose between title and excerpt may be a possibility. I'll consider it. For everyone else, there's the filter hooks.

**Comment by janboddez** [comment]
> ...also, the permalink would have to be included in the excerpt char count (and blank lines as well) - i guess that makes it a little harder on your end

This is less of an issue than you'd expect. I do believe Mastodon counts URLs as a fixed number of characters (13? 26? I have to look that up) regardless of their actual length. (Their database allows for some "overshoot," I guess you could say.) Still, there might be URLs inside the excerpt. Or right at the end of it, that could still end up getting cut in half. And so on.

**Comment by atomGit** [comment]
how would i put all this together (i'm not a PHP-er)? also, i think instead of adding a plain permalink i'd rather do the 'Read the rest...' thing

so we start with...

```php
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
    $status = wp_strip_all_tags(
    html_entity_decode( get_the_excerpt( $post ), ENT_QUOTES | ENT_HTML5, get_bloginfo( 'charset' ) )
  );
  $status .= "\n\n" . get_permalink( $post );
  return $status;
}, 10, 2 );
```

...but where does this need to go - can this be combined with the above?...

`add_filter( 'share_on_mastodon_cutoff', '__return_true' );`

> I do believe Mastodon counts URLs as a fixed number of characters (13? 26? ...

they truncate links to [23 chars](https://docs.joinmastodon.org/user/posting/) in the UI, but i don't know how that's handled at the API level

**Comment by janboddez** [comment]
So, for now, you could probably create a `mu-plugins` folder inside `wp-content` (if it's not already there).

In it, you would create a new PHP file, like `my-site.php` (the actual file name is _not_ important), with the following contents:
```
<?php

/**
 * Toot excerpts rather than post titles
 */
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
  $status = wp_strip_all_tags(
    html_entity_decode( get_the_excerpt( $post ), ENT_QUOTES | ENT_HTML5, get_bloginfo( 'charset' ) )
  );
  $status .= "\n\n" . get_permalink( $post );
  return $status;
}, 10, 2 );

/**
 * Prevent statuses longer than 500 chars
 */
add_filter( 'share_on_mastodon_cutoff', '__return_true' );
```

Again, relative to your WordPress (or ClassicPress) install, the file path would be `wp-content/mu-plugins/my-site.php`.

If you really wanted actual link text instead of a plain-text URL, Mastodon may (or should) support `a` tags (cf. https://docs.joinmastodon.org/spec/activitypub/#sanitization). That said, I haven't actually got it to work before and would have to do some experimenting first.

The nice thing about plain-text URLs is that Mastodon will still automatically create preview cards and such, so I don't consider them too bad. Also, from an accessibility POV, you'll probably want the link text to be a bit more than just "Read more" (or similar).

**Comment by atomGit** [comment]
ok, i put all this together and it *almost* worked :)

my WP post...
TITLE: test post
CONTENT: blah
TAGS: sometag

posted on Mastodon...
TITLE:
CONTENT: <permalink>
TAGS: \#sometag

so the title and content were missing - here's the code...

```php
<?php

/* Toot excerpts rather than post titles */
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
    $status = wp_strip_all_tags(
        html_entity_decode( get_the_excerpt( $post ), ENT_QUOTES | ENT_HTML5, get_bloginfo( 'charset' ) )
    );
    $status .= "\n\n" . get_permalink( $post );
    return $status;
}, 10, 2 );

/* publish post tags as Mastodon hashtags */
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
    $tags = get_the_tags( $post->ID );
    if ( $tags ) {
        $status .= "\n\n";
        foreach ( $tags as $tag ) {
        $status .= '#' . preg_replace( '/\s/', '', $tag->name ) . ' ';
        }
        $status = trim( $status );
    }
    return $status;
}, 11, 2 );

/* Prevent statuses longer than 500 chars */
add_filter( 'share_on_mastodon_cutoff', '__return_true' );
```

**Comment by janboddez** [comment]
This works for me:
```
<?php

/* Prevent statuses longer than 500 chars */
add_filter( 'share_on_mastodon_cutoff', '__return_true' );

/* Override default status format */
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
    // Include title, excerpt, and permalink
    $status  = get_the_title( $post );
    $status .= "\n\n" . apply_filters( 'the_excerpt', get_the_excerpt( $post ) ) . "\n\n";
    $status .= 'Read more: ' . get_permalink( $post );

    // Prevent double-encoded entities and such
    $status = wp_strip_all_tags(
        html_entity_decode( $status, ENT_QUOTES | ENT_HTML5, get_bloginfo( 'charset' ) )
    );

    // Append tags, if any
    $tags = get_the_tags( $post->ID );

    if ( $tags ) {
        $status .= "\n\n";

        foreach ( $tags as $tag ) {
            $status .= '#' . preg_replace( '/\s+/', '', $tag->name ) . ' ';
        }

        $status = trim( $status );
    }

    return $status;
}, 10, 2 );

```

**Comment by janboddez** [comment]
(Not to self) Consider the following alternative (a competely custom message): https://jetpack.com/support/publicize/#sharing-new-posts.

**Comment by atomGit** [comment]
thanks, but i'd rather not use jetpack - i think that's a lot of extra bloat

**Comment by janboddez** [comment]
Going to close. Filters, although they require some PHP knowledge, already allow every type of customization possible, and a Jetpack-like "excerpt that isn't the actual excerpt" is probably not going to happen anytime soon, either.
