### ISSUE TITLE
url validation

### ISSUE THREAD

**Issue by harcesz** [janboddez/share-on-mastodon#15]
in configuration if the instance URL is given without https:// the process fails without any warning.

it would be better, if it automatically tried with https:// or warned it's required

**Comment by janboddez** [comment]
Good call!

I'll add an error message in a next release, and maybe some client-side check (like `type="url"` on the input field) that should suffice to prevent accidental errors. (The latter would probably gladly accept something like http://user:pass@localhost:8080, which WordPress's HTTP API may not, but I'm going to consider that a pretty exotic use case.)

I like the idea of automatically adding `https://` but doubt it's sufficiently transparant—an actual error message plus upfront warning is probably more clear.

**Comment by janboddez** [comment]
Addressed in 8d286b63bde7d4d03639b7b12a18e2432d9c8418.
