### ISSUE TITLE
No posts withj WP Script Theme

### ISSUE THREAD

**Issue by diehummel** [janboddez/share-on-mastodon#18]
Hello,

i have installed the Mastodon Wordpress Plugin and use with a WP Script Theme.

I want to autopost embbed video posts.

But the Plugin does not work for me. Also all other Mastodon Plugins don't work.

I can select "Videos" in the settings, but it has no effect.

I also enabled the debug, but there was no entry for this plugin.
Looked like it was not called after publishinig a new post.

br

Christian

**Comment by diehummel** [comment]
With the filter from the other issue
add_filter( 'share_on_mastodon_enabled', '__return_true', 999 );
 
it works too.

**Comment by janboddez** [comment]
That would indicate the checkbox isn't checked (or even displayed) on the Post Edit screen. Kind of looks like this (when using the Classic Editor):
![image](https://user-images.githubusercontent.com/8428432/104696925-42b1b300-570f-11eb-9cdd-dfed2927603a.png)
If your post type uses the Block Editor, it looks almost the same and should appear under the Post tab in the Settings column. 
![image](https://user-images.githubusercontent.com/8428432/104697524-2eba8100-5710-11eb-8e39-ee0ba3aa78f3.png)
(Ignore the different language, image is from another site.)

Perhaps your post type has somehow disabled these "meta boxes"; if so, using the filter is a valid workaround/solution. (If needed, it can be made smarter, too, but that requires a bit of PHP knowledge.)

**Comment by diehummel** [comment]
Hi,
i checked the flag now on a new automated post and it is set
![grafik](https://user-images.githubusercontent.com/18324187/104698442-a9d06700-5711-11eb-9ef8-765f2aedb555.png)

I am using the Block Editor, but the post are posted automatically.

**Comment by diehummel** [comment]
Maybe the flag is "too late" during the automisation.

**Comment by janboddez** [comment]
I see. Yes, due to how things are implemented, the flag (even though it appears checked) is only saved if the Edit Screen form is _actually submitted_ (i.e., the Publish or Save Changes button pressed).

For posts that are published automatically _or_ created through a 3rd-party app, the filter is needed.

**Comment by diehummel** [comment]
thanks for clarifying.
