### ISSUE TITLE
Tag in post 

### ISSUE THREAD

**Issue by b4zz4** [janboddez/share-on-mastodon#2]
This plugon take the tags of the publication and add it to the publication of mastodon

**Comment by janboddez** [comment]
If you wanted to automatically append tags (as hashtags) to a Mastodon status, you _could_ do that as follows (add to your theme's `functions.php`):
```
add_filter( 'share_on_mastodon_status', function( $status, $post ) {
  $tags = get_the_tags( $post->ID );

  if ( $tags ) {
    $status .= PHP_EOL . PHP_EOL;
    
    foreach ( $tags as $tag ) {
      $status .= '#' . preg_replace( '/\s/', '', $tag->name ) . ' ';
    }

    $status = trim( $status );
  }

  return $status;
}, 10, 2 );
```
I might include something similar in the next version of the plugin.

**Comment by b4zz4** [comment]
Very good :D
