### ISSUE TITLE
The Post is shared on Mastodon only if manually edited

### ISSUE THREAD

**Issue by mmontuori** [janboddez/share-on-mastodon#20]
The Post is shared on Mastodon only if manually edited. If a Post is created with API without the editor, the Post is not shared. You have to go manually and Update the article to be shared.

**Comment by janboddez** [comment]
Correct. You can force sharing, however, by adding the following to, e.g., your theme's `functions.php`.
```
// Always share supported Post Types.
add_filter( 'share_on_mastodon_enabled', '__return_true' );
```
This filter supports additional parameters, too (like, if you wanted to share only certain categories, etc.): https://jan.boddez.net/wordpress/share-on-mastodon#share_on_mastodon_enabled.

**Comment by mmontuori** [comment]
Excellent! Worked perfectly. Thanks for posting the code snippet. Closing issue...
