### ISSUE TITLE
Additional settings

### ISSUE THREAD

**Issue by janboddez** [janboddez/share-on-mastodon#25]
Need additional settings for items that now exist only through filters:

- Crosspost always (i.e., for those posting exclusively from mobile apps)
- Enable/disable featured/attached images
- Enable/disable delayed posting (in case, e.g., posts created through a mobile app don't go through)
- Post privacy (lower prio, as we assume people share their posts to reach as wide as possible an audience)

**Comment by edent** [comment]
I'd love to just share the featured image. At the moment it seems to send up to 4 images per post.

**Comment by rfischmann** [comment]
If we disable featured/attached images, does it show a post card/preview with its title, excerpt and a small featured image? I think I rather it worked like that. Thanks!

**Comment by janboddez** [comment]
> If we disable featured/attached images, does it show a post card/preview with its title, excerpt and a small featured image? I think I rather it worked like that. Thanks!

Mastodon normally generates these previews, yes. If the link is there and you'd have the proper Open Graph, etc. tags in place.

**Comment by rfischmann** [comment]
> > If we disable featured/attached images, does it show a post card/preview with its title, excerpt and a small featured image? I think I rather it worked like that. Thanks!
> 
> Mastodon normally generates these previews, yes. If the link is there and you'd have the proper Open Graph, etc. tags in place.

Yep, it's working fine after removing the images. Thanks, @janboddez!

That should indeed be a setting for the plugin.

**Comment by janboddez** [comment]
Not adding the visibility setting (there's a filter for it anyway). The rest is part of 0.11.0.

**Comment by janboddez** [comment]
Not adding the visibility setting (there's a filter for it anyway). The rest is part of 0.11.0.
