### ISSUE TITLE
Excluding categories

### ISSUE THREAD

**Issue by davemreed** [janboddez/share-on-mastodon#31]
Thanks for your work on this plugin. Is it possible to exclude specified categories from posting to Mastodon?

**Comment by janboddez** [comment]
It is (or should be)! If you're familiar with modding WordPress sites through your theme's `functions.php` or a (mu-)plugin, here's one way of doing so:
```
add_filter( 'share_on_mastodon_enabled', function( $is_enabled, $post_id ) {
  if ( has_category( 'my-category-slug', $post_id ) ) {
    // Do not share posts in `my-category-slug`.
    return false;
  }

  return $is_enabled;
}, 10, 2 );
```
As per the example on https://jan.boddez.net/wordpress/share-on-mastodon#share_on_mastodon_enabled

**Comment by davemreed** [comment]
I read that page and totally spaced over that example, thanks!

**Comment by janboddez** [comment]
Yeah, I should update that. It still works as before (and comes after all other checks, and is no longer deprecated).
