### ISSUE TITLE
no share if scheduled post is published

### ISSUE THREAD

**Issue by MaxED9** [janboddez/share-on-mastodon#40]
Hi,

in most case I schedule my posts, but the plugin doesn't share it if the publish time is reached and the post online.
If I edit and update the post, it works fine.

**Comment by janboddez** [comment]
Do you use a mobile app or WordPress itself for creating/scheduling these posts?

If you use WP’s admin interface, there should be a "meta box" with a checkbox in it. When the post is first saved, its value is remembered.

If you create posts from another application (like a mobile app), WP never "sees" this checkbox, _until_ you revisit the post in WP Admin.

If that's the case, there are several things you could do, see also: https://jan.boddez.net/wordpress/share-on-mastodon#share_on_mastodon_enabled

**Comment by MaxED9** [comment]
Hi Jan,

thanks for your reply. I use only the WP backend, no third party or mobile WP app.
The checkbox is/was checked. But maybe the reason could be that I installed the plugin after I scheduled the posts. 🤔

I will keep an eye on it, having now new posts in the pipeline.

**Comment by janboddez** [comment]
Ah, that would explain.

Yes, the checkbox is always enabled when a post is first created (unless you apply the filter hook to make it opt-in). But its value is only **saved** to the database when the post itself is saved. This gives you the chance to **not** share, by unchecking it before you hit Publish (or Schedule).

**Comment by MaxED9** [comment]
Hi again,

worked fine with a new scheduled post.

thanks for your help

**Comment by janboddez** [comment]
You're welcome, glad the plugin is working for you!
