### ISSUE TITLE
Alt Text on Images

### ISSUE THREAD

**Issue by bgrinter** [janboddez/share-on-mastodon#42]
New to Mastodon and enjoying using this to share from WordPress

I see Alt text on images is a big thing on Mastodon, is there a way to add this?

**Comment by timnolte** [comment]
You need to add alt text on your images in WordPress like normal, and then that carries over to Mastodon just fine. The key concept is that alt text shouldn't be seen as being just a Mastodon thing.

**Comment by janboddez** [comment]
That is correct. If an image has an alt text in WordPress's media library, it should just show up on Mastodon as well.

For those interested, it is covered by the following by https://github.com/janboddez/share-on-mastodon/blob/4353e6bbb8092651d27edc46a879301f79cee3e4/includes/class-post-handler.php#L451 and the code that immediately follows it.
