### ISSUE TITLE
Emoji in post titles (maybe bug? maybe my fault? maybe a feature request?)

### ISSUE THREAD

**Issue by djwudi** [janboddez/share-on-mastodon#45]
I just got this installed and working, but have discovered a minor issue — I use emoji in my blog post titles, but they seem to be getting mangled and are instead just appearing in the Mastodon post as the raw HTML entity and partially turned into a Mastodon tag.

Example:
* Original blog post title: [🎥 Elvis](https://michaelhans.com/eclecticism/2022/12/26/🎥-elvis/)
* As displayed in the Mastodon post: [\&#x1f3a5; Elvis](https://tenforward.social/@djwudi/109582850979694913)

I'm not sure if this is a bug somewhere in the plugin, a bug of my own making in [the PHP code I came up with](https://michaelhans.com/eclecticism/2022/12/26/cross-posting-from-wordpress-to-mastodon/) for making the Mastodon post look the way I want, or if this is just something that could be resolved in a future update.

Any assistance would be appreciated! Thanks!

**Comment by janboddez** [comment]
I think `get_the_title()` returns HTML-encoded emoji (and quotes, and so on). And Mastodon then escapes that code, i.e., turns the literal `&` into `&amp;`.

Looking at the source code of your website:
![image](https://user-images.githubusercontent.com/8428432/209647994-fa61d4f9-3621-4ba2-8c44-571dc9661f90.png)

What might help is decode entities back to "raw" Unicode, so use `html_entity_decode( get_the_title( $post ) )`. Or better still, just unescape the whole thing just before returning it `return html_entity_decode( $status )`.

Depending on your site's character encoding, you may need to pass a 2nd and 3rd parameter to `html_entity_decode()`, but 9 times out of then this is enough.

**Comment by janboddez** [comment]
Just thought I'd have to fix this in the plugin itself, too, but behold :-): https://github.com/janboddez/share-on-mastodon/blob/7b2e5b4edc44df8280086edf3fe2657e80522fab/includes/class-post-handler.php#L327

**Comment by djwudi** [comment]
Thanks so much, Jan! The single-line fix of adding `return html_entity_decode( $status )` did the trick. Thanks for the quick and on-point response!
