### ISSUE TITLE
Error status

### ISSUE THREAD

**Issue by davehill47** [janboddez/share-on-mastodon#50]
Sometimes a post will simply not generate a share to my Mastodon account, and the only way I am aware of that is if (a) the post never shows up on Masto, and (b) the URL for the Masto link doesn't show up in the metabox.  But ... there's indication of why it didn't work -- error communicating with server, or message was inexplicable too long or what. If there is a failure, could we get some sort of indication of the cause in the metabox?

**Comment by janboddez** [comment]
Ah, that sounds like a good idea.

Whenever my posts don't go through, it's usually that they're too long, which I can live with, but depending on your server, it could be our timeout's too tight, etc.

Errors/server responses _are_ logged to "debug.log," if debug logging's enabled (it probably shouldn't, on production servers), so if you're somewhat good with WordPress's tech side, you could give that a try.

But a more user-friendly status update is definitely something to consider.

**Comment by janboddez** [comment]
Added in c95915064291054d97f8718766280e9468a9e8e8. Published in v0.10.0.
