### ISSUE TITLE
Supporting Syndication Links plugin

### ISSUE THREAD

**Issue by jasontucker** [janboddez/share-on-mastodon#69]
I'm curious if you have tried the Syndication Links plugin and if you have looked into may  supporting it with this plugin? The idea is when a post made on Mastodon the resulting url is saved for this plugin to display on the site. Curious what your thought are on this and if it would be something you could support.

https://wordpress.org/plugins/syndication-links/

Here is how one of the supported plugins is doing it
https://github.com/fabacab/wp-crosspost/blob/83df3c04add331d9688f8b24b074c81007a9686c/wp-crosspost.php#L120
and another one (by the same author)
https://github.com/fabacab/diasposter/blob/4a39a8b3dbf2a28e7c802f6175b65b4b68221fc8/diasposter.php#L56

Here is a list of plugins supporting this:

SUPPORTED POSSE PLUGINS AND IMPLEMENTATIONS
The plugin supports automatically pulling data from plugins that syndicate your content so you don’t need to do it manually. For anything not built in, integation is easy with a simple filter for potential use with any other plugin.

[Social Networks Autoposter](https://wordpress.org/plugins/social-networks-auto-poster-facebook-twitter-g/) – Syndication Links supports Twitter, Facebook, and Tumblr since version 1.0.0
[Tumblr Crosspostr](https://wordpress.org/plugins/tumblr-crosspostr) – Supports Syndication Links since version 0.8.1
[WordPress Crossposter](https://wordpress.org/plugins/wp-crosspost) – Supports Syndication Links since version 0.3.2
[Diasposter](https://wordpress.org/plugins/diasposter/) – Supports Syndication Links since version 0.1.8
[WP-To_Twitter](https://wordpress.org/plugins/wp-to-twitter/) – Supported by the plugin since version 4.2.3

**Comment by janboddez** [comment]
Did you already give this a try? Provided both plugins are installed?

![image](https://user-images.githubusercontent.com/8428432/233931123-3e756dc0-fb6f-4143-ba61-e9cebc4ae103.png)

**Comment by janboddez** [comment]
What that does is, Syndication Links automatically appends this list of syndicated links, and this setting will filter that list, adding in Mastodon links from "Share on Mastodon."

You could do other things using hooks and such, but this is I think the basic functionality you may be looking for.

The other plugin of mine, IndieBlocks, does it the other way around. It comes with a Syndication _block_ (so no auto-appending to _post content_) that out of the box supports Share on Mastodon/Pixelfed but can be filtered to include Syndication Links or other URLs. (I have to basically rewrite the documentation for all these plugins, but ... time ...)

**Comment by jasontucker** [comment]
Ah, looks like I was using the released plugin from the plugin directory and not the dev one. 🥇 I'll give this a try and see how it works for me.

**Comment by janboddez** [comment]
I was sort of convinced this was already in the released version ... but I'm way behind with all that stuff. I'll look into it.

**Comment by janboddez** [comment]
To do: use the newer filter, see also https://github.com/janboddez/indieblocks/issues/85.

**Comment by janboddez** [comment]
Fixed in [d1107fe](https://github.com/janboddez/share-on-mastodon/commit/d1107fe7dd66799e825cfffcf561320045d9c9bd).
